"""LLM -> skill -> tools mapping for the D-drive runtime only."""

LLM_SKILL_TOOL_MAP = {
    "general_planner_llm": {
        "skills": {
            "ChatPlanningSkill": [
                "core.engine.ask",
                "core.engine.prepare_context",
                "retrieval.intent_classifier.classify_intent_with_confidence",
                "retrieval.hybrid_retriever.search_tools",
                "retrieval.hybrid_retriever.search_examples",
            ],
            "ToolDiscoverySkill": [
                "tool_detail",
                "tool_io_spec",
                "tool_compatibility",
                "cpu_tools",
                "flow_plan_debug",
            ],
            "QCPreprocessSkill": [
                "29-Summarize-slide-info",
                "30-Get-slide-previews",
                "40-GrandQC",
                "28-Stain-Normalization",
                "52-Global-Macenko",
                "57-estimate-image-spacing",
                "1-foreground-segmentation",
                "48-foreground-segmentation-beta",
            ],
            "SegmentationDetectionSkill": [
                "2-lung-cancer-segmentation",
                "3-tissue-segmentation",
                "11-CD34-vessel-segmentation",
                "12-PAS-kidney-glomeruli-segmentation",
                "13-intrahepatic-cholangiocarcinoma-tissue-segmentation",
                "16-liver-tissue-segmentation",
                "17-lung-tertiary-lymphoid-structures-segmentation",
                "18-PAS-kidney-glomeruli-multi-class-segmentation",
                "26-Kidney-Masson-4-class-segmentation",
                "35-Train-segmentation-baseline",
                "36-Infer-segmentation-baseline",
                "60-tissue-segmentation-trial",
                "64-TUZI",
                "68-Train-segmentation-pipeline-from-slides-xml",
                "69-Train-segmentation-pipeline-from-slides-mask",
                "70-Infer-segmentation-pipeline",
                "5-pancreas-tumor-detection",
                "6-breast-tumor-detection",
                "7-gastric-tumor-detection",
                "8-colon-tumor-detection",
                "9-endometrium-tumor-detection",
                "10-ovarian-tumor-detection",
                "14-intrahepatic-cholangiocarcinoma-cancer-detection",
                "51-ssl-luad-classification",
                "62-pancancer-detection-20",
                "63-pancancer-detection-40",
                "75-Gleason-AGGC",
            ],
            "NucleusPathomicsSkill": [
                "4-nucleus-segmentation-hovernet-pannuke",
                "50-hovernet-pannuke-mp",
                "53-hover-next-mp",
                "49-slide-embedding-all-methods",
                "76-Pathomics-pipeline-from-slides",
                "77-Pathomics-pipeline-from-slides-nucleus",
            ],
        },
    },
    "paper_reasoning_llm": {
        "skills": {
            "PaperEvidenceSkill": [
                "papers_search",
                "paper_upload",
                "paper_library",
                "paper_favorites",
                "paper_analyze",
                "paper_toolchain_plan",
                "paper_toolchain_evidence",
                "paper_toolchain_export",
                "paper_toolchain_reproducibility",
            ],
            "ImmuneTMESkill": [
                "39-HE-transfer-to-SHG",
                "41-Deepliif",
                "42-CycleGAN-Norm-Xiacong",
                "48-foreground-segmentation-beta",
                "61-hooknet-tls",
                "65-PSPStain",
                "66-HistoPlexer",
                "67-GigaTIME",
                "17-lung-tertiary-lymphoid-structures-segmentation",
            ],
            "MILMultimodalSkill": [
                "15-Cerberus",
                "71-Train-MIL-pipeline-from-slides",
                "72-Train-MIL-pipeline-from-h5",
                "73-Infer-MIL-pipeline-for-slides",
                "74-Infer-MIL-pipeline-for-h5",
                "78-Train-MIL-multi-modal-pipeline-from-slides",
                "79-Train-MIL-multi-modal-pipeline-from-h5",
                "80-Infer-MIL-multi-modal-pipeline-for-slides",
                "81-Infer-MIL-multi-modal-pipeline-for-h5",
            ],
        },
    },
    "execution_control_llm": {
        "skills": {
            "ExecutionSkill": [
                "tool_execute",
                "flow_prepare",
                "approval_intent",
                "execution_preflight",
                "flow_execute_real",
                "scheduler_submit",
                "scheduler_get",
                "scheduler_cancel",
                "scheduler_events",
            ],
            "TroubleshootingReadbackSkill": [
                "result_manifest_inspect",
                "result_file_preview",
                "result_file_download",
                "tool_result_review",
                "open_reasoning_diagnostics",
            ],
            "AnnotationPrepSkill": [
                "23-SAM-point-annotation",
                "24-SAM2.1-point-annotation",
                "25-BiomedParse",
                "31-Summarize-asap-xml-info",
                "32-Transfer-asap-xml-to-tif",
                "33-Generate-segmentation-patches",
                "34-Generate-classification-patches",
                "38-Text-Encoding",
                "54-kfb2svs",
                "55-pkl2h5",
                "56-image2tif",
                "58-value-mapping",
                "59-generate-overlays",
            ],
        },
    },
    "workspace_memory_llm": {
        "skills": {
            "ArchiveSkill": [
                "archive_session",
                "get_session_record",
            ],
            "SessionConversationSkill": [
                "session_bootstrap",
                "session_new",
                "session_history",
                "session_reset",
                "session_archive",
                "session_archive_user_index",
                "conversation_list",
                "conversation_get",
                "conversation_patch",
                "conversation_add_message",
            ],
            "ProjectWorkspaceSkill": [
                "project_create",
                "project_list",
                "project_update",
                "project_delete",
                "project_pin",
                "project_archive",
                "project_scan",
                "project_materials",
                "project_sessions_bind",
                "project_sessions_unbind",
                "project_paper_folders_bind",
                "project_paper_folders_unbind",
                "project_session_map",
                "asset_upload",
                "asset_download",
            ],
            "UploadRecoverySkill": [
                "upload_file",
                "upload_chunk_init",
                "upload_chunk_save",
                "upload_chunk_complete",
                "upload_recover",
                "uploaded_file_download",
                "uploaded_file_preview",
            ],
            "ToolDiscoverySkill": [
                "tool_detail",
                "tool_io_spec",
                "tool_compatibility",
            ],
            "PaperEvidenceSkill": [
                "paper_library",
                "paper_favorites",
                "paper_toolchain_evidence",
            ],
        },
    },
    "platform_ops_llm": {
        "skills": {
            "SchedulerOpsSkill": [
                "scheduler_submit",
                "scheduler_get",
                "scheduler_cancel",
                "scheduler_events",
                "scheduler_local_run_next",
                "ops_cluster_status",
                "ops_jobs_list",
                "ops_job_get",
                "ops_job_events",
                "ops_queue_metrics",
                "ops_quota_summary",
                "ops_metrics_overview",
            ],
            "InternalFlowHarnessSkill": [
                "internal_flow_health",
                "internal_flow_prepare",
                "internal_flow_preflight",
                "internal_flow_jobs",
                "internal_flow_fake_runs",
                "internal_flow_manifest_inspection",
                "internal_flow_result_manifest_inspection",
                "internal_flow_executor_state",
                "internal_flow_contract_version",
                "internal_flow_smoke_status",
            ],
            "AuthIdentitySkill": [
                "auth_register",
                "auth_login",
                "auth_login_phone",
                "auth_refresh",
                "auth_logout",
                "auth_me_get",
                "auth_me_update",
                "auth_mfa_enroll_start",
                "auth_mfa_enroll_confirm",
                "auth_mfa_verify",
                "auth_recovery_start",
                "auth_recovery_confirm",
                "auth_verification_send",
            ],
        },
    },
}

